---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-b1731322476994
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-b1731322476994 
  name: chatbot-b1731322476994
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi