apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chatbot-b1731322476994
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-b1731322476994 
  name: chatbot-b1731322476994
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-b1731322476994 
