apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-b1731322476994
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/chbot:190dd3eec4fd4fb1381d9fc20ae157f5e8358e8d@sha256:d6d38d514ccdc956eb40c6627b1fb429d43e1b734da474494ff30516dfdb28d1 # use pre-built to bootstrap 
          name: app-inference
